// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDABrxQmlEcU4_wCj0fbg0YGi2x391tfm0',
    appId: '1:622827436592:web:343d70f7da6ffafb9d8bf5',
    messagingSenderId: '622827436592',
    projectId: 'proj-firebase-55c6d',
    authDomain: 'proj-firebase-55c6d.firebaseapp.com',
    storageBucket: 'proj-firebase-55c6d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAS2-62gpaxsgI7now-hQu9_l7NHR2lcs',
    appId: '1:622827436592:android:ea8cff06a0a3a4a19d8bf5',
    messagingSenderId: '622827436592',
    projectId: 'proj-firebase-55c6d',
    storageBucket: 'proj-firebase-55c6d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_7Je7uAj3jgm21I8L5mhJj6oyfJUtJ-A',
    appId: '1:622827436592:ios:b4648a8fb815139e9d8bf5',
    messagingSenderId: '622827436592',
    projectId: 'proj-firebase-55c6d',
    storageBucket: 'proj-firebase-55c6d.firebasestorage.app',
    iosBundleId: 'com.example.projFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_7Je7uAj3jgm21I8L5mhJj6oyfJUtJ-A',
    appId: '1:622827436592:ios:b4648a8fb815139e9d8bf5',
    messagingSenderId: '622827436592',
    projectId: 'proj-firebase-55c6d',
    storageBucket: 'proj-firebase-55c6d.firebasestorage.app',
    iosBundleId: 'com.example.projFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDABrxQmlEcU4_wCj0fbg0YGi2x391tfm0',
    appId: '1:622827436592:web:78e76d0706e07a699d8bf5',
    messagingSenderId: '622827436592',
    projectId: 'proj-firebase-55c6d',
    authDomain: 'proj-firebase-55c6d.firebaseapp.com',
    storageBucket: 'proj-firebase-55c6d.firebasestorage.app',
  );
}
